name: Deploy Public Files

on:
  push:
    branches:
      - main  # أو الفرع الذي تريد التحديث منه

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout private repo
        uses: actions/checkout@v4

      - name: Clone public repo
        run: |
          git clone https://github.com/AbdalrahmanEmara/public-repo.git public_repo
          cd public_repo
          git config user.name "github-actions[bot]"
          git config user.email "github-actions@github.com"

      - name: Copy public files
        run: |
          rm -rf public_repo/*
          cp -r public_folder/* public_repo/
          cd public_repo
          git add .
          git commit -m "Auto update from private repo"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/YOUR-USERNAME/public-repo.git main
